robot_name: xarm

# Detector used to teleoperate the robot
detector:
  _target_: src.components.detector.oculusbimanual.OculusVRTwoHandDetector
  host: ${host_address}
  oculus_right_port: ${oculus_reciever_port}
  oculus_left_port: ${left_hand_receiver_port}
  keypoint_pub_port: ${keypoint_port}

# Transformation classes used to transform the keypoints
transforms:
  -
    _target_: src.components.detector.keypoint_transform.TransformHandPositionCoords
    host: ${host_address}
    keypoint_port: ${keypoint_port}
    transformation_port: ${transformed_position_keypoint_port}
    moving_average_limit: 1
    is_right: True
    log: ${log}
  -
    _target_: src.components.detector.keypoint_transform.TransformHandPositionCoords
    host: ${host_address}
    keypoint_port: ${keypoint_port}
    transformation_port: ${transformed_position_left_keypoint_port}
    moving_average_limit: 1
    is_right: False
    log: ${log}

transmitters:
  - 
    _target_: src.components.transmitter.switch.Switch
    host: ${host_address}
    transformed_right_keypoints_port: ${transformed_position_left_keypoint_port}
    switch_state_port: ${switch_state_port}
    record_varify_port: ${record_varify_port}
  -
    _target_: src.components.transmitter.xarm_info_transmitter.XarmInfoNotifier
    host: ${host_address}
    transformation_port: ${transformed_position_keypoint_port}
    xarm_info_transmitter_port: ${xarm_info_transmitter_port}
    xarm_ip: ${xarm_ip}
    action_port: ${action_port}


# Operators used to retarget the keypoints
operators:
  - 
    _target_: src.components.operators.xarm.XarmOperator
    host: ${host_address}
    transformed_keypoints_port: ${transformed_position_keypoint_port}
    operation_stage_port: ${operation_stage_port}
    action_port: ${action_port}
    xarm_ip:  ${xarm_ip}
    comp_ratio: 0.5
    # log: True

# List of controller classes used
controllers:
  -
    _target_: src.robot.xarm.Xarm
    record: False


# Information to be recorded by the robot 
recorded_data:
  - 
    - joint_states
    - cartesian_states