robot_name: xarm

# Detector used to teleoperate the robot
detector:
  _target_: src.components.detector.oculus.OculusVRHandDetector
  host: ${host_address}
  oculus_port: ${left_hand_receiver_port}
  keypoint_pub_port: ${keypoint_port}
  is_right: ${is_right}
  log: True

# Transformation classes used to transform the keypoints
transforms:
  -
    _target_: src.components.detector.keypoint_transform.TransformHandPositionCoords
    host: ${host_address}
    keypoint_port: ${keypoint_port}
    transformation_port: ${transformed_position_keypoint_port}
    moving_average_limit: 1
    is_right: ${is_right}


# Operators used to retarget the keypoints
operators:
  - 
    _target_: src.components.operators.xarm.XarmOperator
    host: ${host_address}
    transformed_keypoints_port: ${transformed_position_keypoint_port}
    xarm_ip: '10.177.63.209'
    scale_vector: [1000,1000,1000]
    comp_ratio: 0.5
    # log: True
    is_right: ${is_right}

# List of controller classes used
controllers:
  -
    _target_: src.robot.xarm.Xarm
    record: False


# Information to be recorded by the robot 
recorded_data:
  - 
    - joint_states
    - cartesian_states