defaults:
  - _self_
  - network
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 

camera_info:
  -
    name: "robot_camera"
    serial_number: '233522078536'
    stream_rescale_factor: 3 # 424 * 240
  - 
    name: "human_camera"
    serial_number: "236422070023"
    stream_rescale_factor: 3

oculus_cam: 0 # First camera
num_cams: 2

cam_configs:
  width: 1280
  height: 720
  fps: 30
  # processing_preset: 1 # High accuracy mode
  processing_preset: 0
  rotation_angle: 0

hydra:  
  output_subdir: null  
  run:  
    dir: .
