defaults:
  - _self_
  - network
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

recorder:
  - 
    _target_: src.components.recorder.vr_operation.VROperationRecorder
    host: ${host_address}
    listen_port: ${xarm_info_transmitter_port}
    switch_state_port: ${switch_state_port}
    save_path: "dataset/grab_cup"
    template: "episode_{}.hdf5"
    record_varify_port: ${record_varify_port}
